import { colors } from '@/constants/theme';
import { WorkoutTemplate } from './templateStore';

// Category images for preset templates
const CATEGORY_IMAGES = {
  core: require('../../assets/images/ABS-CORE/IMG_4464.JPG'),
  glutes: require('../../assets/images/GLUTES/IMG_4472.JPG'),
  lowerBody: require('../../assets/images/LOWER BODY/IMG_4484.JPG'),
  pull: require('../../assets/images/BACK-PULL/IMG_4451.JPG'),
  push: require('../../assets/images/UPPER BODY/IMG_4492.JPG'),
  upperBody: require('../../assets/images/UPPER BODY/IMG_4493.JPG'),
} as const;

// Helper to create 3 default sets
const s3 = (r1: number, r2: number, r3: number, w1?: number, w2?: number, w3?: number) =>
  w1 != null
    ? [
        { setNumber: 1, targetWeight: w1, targetReps: r1 },
        { setNumber: 2, targetWeight: w2 ?? w1, targetReps: r2 },
        { setNumber: 3, targetWeight: w3 ?? w2 ?? w1, targetReps: r3 },
      ]
    : [
        { setNumber: 1, targetReps: r1 },
        { setNumber: 2, targetReps: r2 },
        { setNumber: 3, targetReps: r3 },
      ];

// Preset templates organized by 6 categories
export const PRESET_TEMPLATES: WorkoutTemplate[] = [
  // ===========================
  // CORE (8 workouts)
  // ===========================
  {
    id: 'preset-core-1',
    name: 'Machines',
    description: 'Machine-based core workout targeting all abdominal muscles',
    tagIds: ['core'],
    tagColor: colors.workout.core,
    estimatedDuration: 35,
    difficulty: 'Intermediate',
    equipment: 'Gym',
    category: 'core',
    localImage: CATEGORY_IMAGES.core,
    exercises: [
      {
        id: '1',
        exerciseId: 'cable-crunches-kneeling',
        exerciseName: 'Cable Crunches (Kneeling)',
        muscle: 'Core',
        sets: s3(15, 12, 12, 20, 25, 25),
        restTimerSeconds: 60,
      },
      {
        id: '2',
        exerciseId: 'pallof-press',
        exerciseName: 'Pallof Press',
        muscle: 'Core',
        sets: s3(12, 10, 10, 10, 12, 12),
        restTimerSeconds: 60,
      },
      {
        id: '3',
        exerciseId: 'cable-rotations',
        exerciseName: 'Cable Rotations',
        muscle: 'Core',
        sets: s3(12, 10, 10, 10, 12, 12),
        restTimerSeconds: 60,
      },
      {
        id: '4',
        exerciseId: 'decline-sit-ups',
        exerciseName: 'Decline Sit Ups',
        muscle: 'Core',
        sets: s3(15, 12, 12),
        restTimerSeconds: 60,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'preset-core-2',
    name: 'Dumbbells',
    description: 'Dumbbell core workout for stability and oblique strength',
    tagIds: ['core'],
    tagColor: colors.workout.core,
    estimatedDuration: 35,
    difficulty: 'Intermediate',
    equipment: 'Gym',
    category: 'core',
    localImage: CATEGORY_IMAGES.core,
    exercises: [
      {
        id: '1',
        exerciseId: 'dumbbell-side-bend',
        exerciseName: 'DB Side Flexion',
        muscle: 'Core',
        sets: s3(12, 10, 10, 10, 12, 12),
        restTimerSeconds: 60,
      },
      {
        id: '2',
        exerciseId: 'isometric-hold-heel-taps',
        exerciseName: 'Isometric Hold with Heel Taps',
        muscle: 'Core',
        sets: s3(12, 12, 10),
        restTimerSeconds: 45,
      },
      {
        id: '3',
        exerciseId: 'farmers-carry',
        exerciseName: 'Farmers Carry',
        muscle: 'Core',
        sets: s3(12, 12, 10, 20, 24, 24),
        restTimerSeconds: 60,
      },
      {
        id: '4',
        exerciseId: 'suitcase-carry',
        exerciseName: 'Suitcase Carry',
        muscle: 'Core',
        sets: s3(12, 12, 10, 16, 20, 20),
        restTimerSeconds: 60,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'preset-core-3',
    name: 'Mat',
    description: 'No equipment mat-based core workout',
    tagIds: ['core'],
    tagColor: colors.workout.core,
    estimatedDuration: 30,
    difficulty: 'Beginner',
    equipment: 'No Equipment',
    category: 'core',
    localImage: CATEGORY_IMAGES.core,
    exercises: [
      {
        id: '1',
        exerciseId: 'dead-bug',
        exerciseName: 'Dead Bugs',
        muscle: 'Core',
        sets: s3(12, 12, 10),
        restTimerSeconds: 30,
      },
      {
        id: '2',
        exerciseId: 'bird-dog',
        exerciseName: 'Bird Dogs',
        muscle: 'Core',
        sets: s3(12, 12, 10),
        restTimerSeconds: 30,
      },
      {
        id: '3',
        exerciseId: 'reverse-crunch',
        exerciseName: 'Reverse Crunches',
        muscle: 'Core',
        sets: s3(15, 12, 12),
        restTimerSeconds: 30,
      },
      {
        id: '4',
        exerciseId: 'leg-raise',
        exerciseName: 'Leg Raises',
        muscle: 'Core',
        sets: s3(12, 10, 10),
        restTimerSeconds: 30,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'preset-core-4',
    name: 'Mix',
    description: 'Mixed equipment core workout combining machines and bodyweight',
    tagIds: ['core'],
    tagColor: colors.workout.core,
    estimatedDuration: 35,
    difficulty: 'Intermediate',
    equipment: 'Gym',
    category: 'core',
    localImage: CATEGORY_IMAGES.core,
    exercises: [
      {
        id: '1',
        exerciseId: 'hanging-knee-raise',
        exerciseName: 'Hanging Knee Crunches',
        muscle: 'Core',
        sets: s3(12, 10, 10),
        restTimerSeconds: 60,
      },
      {
        id: '2',
        exerciseId: 'kneeling-cable-crunch',
        exerciseName: 'Kneeling Cable Crunch',
        muscle: 'Core',
        sets: s3(15, 12, 12, 20, 25, 25),
        restTimerSeconds: 60,
      },
      {
        id: '3',
        exerciseId: 'dead-bug',
        exerciseName: 'Dead Bugs',
        muscle: 'Core',
        sets: s3(12, 12, 10),
        restTimerSeconds: 30,
      },
      {
        id: '4',
        exerciseId: 'ab-roller',
        exerciseName: 'Ab Roller',
        muscle: 'Core',
        sets: s3(10, 10, 8),
        restTimerSeconds: 60,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'preset-core-5',
    name: 'All Muscles',
    description: 'Complete core workout hitting every abdominal muscle',
    tagIds: ['core'],
    tagColor: colors.workout.core,
    estimatedDuration: 40,
    difficulty: 'Intermediate',
    equipment: 'Gym',
    category: 'core',
    localImage: CATEGORY_IMAGES.core,
    exercises: [
      {
        id: '1',
        exerciseId: 'dead-bug',
        exerciseName: 'Dead Bugs',
        muscle: 'Core',
        sets: s3(12, 12, 10),
        restTimerSeconds: 30,
      },
      {
        id: '2',
        exerciseId: 'russian-twist',
        exerciseName: 'Russian Twists',
        muscle: 'Core',
        sets: s3(20, 16, 16),
        restTimerSeconds: 30,
      },
      {
        id: '3',
        exerciseId: 'pallof-press',
        exerciseName: 'Pallof Press',
        muscle: 'Core',
        sets: s3(12, 10, 10, 10, 12, 12),
        restTimerSeconds: 60,
      },
      {
        id: '4',
        exerciseId: 'dumbbell-side-bend',
        exerciseName: 'Side Flexion with DB',
        muscle: 'Core',
        sets: s3(12, 10, 10, 10, 12, 12),
        restTimerSeconds: 60,
      },
      {
        id: '5',
        exerciseId: 'crunch',
        exerciseName: 'Crunches',
        muscle: 'Core',
        sets: s3(20, 15, 15),
        restTimerSeconds: 30,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'preset-core-6',
    name: 'Hard',
    description: 'Advanced core workout for maximum burn',
    tagIds: ['core'],
    tagColor: colors.workout.core,
    estimatedDuration: 45,
    difficulty: 'Advanced',
    equipment: 'No Equipment',
    category: 'core',
    localImage: CATEGORY_IMAGES.core,
    exercises: [
      {
        id: '1',
        exerciseId: 'dead-bug-alternating',
        exerciseName: 'Dead Bugs (Alternating)',
        muscle: 'Core',
        sets: s3(12, 12, 10),
        restTimerSeconds: 30,
      },
      {
        id: '2',
        exerciseId: 'dead-bug-double-leg',
        exerciseName: 'Dead Bugs (Double Leg)',
        muscle: 'Core',
        sets: s3(10, 10, 8),
        restTimerSeconds: 30,
      },
      {
        id: '3',
        exerciseId: 'alternating-leg-lift',
        exerciseName: 'Alternating Leg Lifts',
        muscle: 'Core',
        sets: s3(12, 12, 10),
        restTimerSeconds: 30,
      },
      {
        id: '4',
        exerciseId: 'double-leg-lift',
        exerciseName: 'Double Leg Lifts',
        muscle: 'Core',
        sets: s3(10, 10, 8),
        restTimerSeconds: 30,
      },
      {
        id: '5',
        exerciseId: 'double-leg-lift-reverse-crunch',
        exerciseName: 'Double Leg Lifts into Reverse Crunch',
        muscle: 'Core',
        sets: s3(10, 8, 8),
        restTimerSeconds: 30,
      },
      {
        id: '6',
        exerciseId: 'plank',
        exerciseName: 'Plank',
        muscle: 'Core',
        sets: s3(45, 45, 45),
        restTimerSeconds: 30,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'preset-core-7',
    name: 'Slow Burn',
    description: 'Controlled tempo core workout for deep burn',
    tagIds: ['core'],
    tagColor: colors.workout.core,
    estimatedDuration: 45,
    difficulty: 'Intermediate',
    equipment: 'No Equipment',
    category: 'core',
    localImage: CATEGORY_IMAGES.core,
    exercises: [
      {
        id: '1',
        exerciseId: 'table-top-crunch',
        exerciseName: 'Table Top Crunches',
        muscle: 'Core',
        sets: s3(15, 12, 12),
        restTimerSeconds: 30,
      },
      {
        id: '2',
        exerciseId: 'bicycle-crunch',
        exerciseName: 'Bicycle Crunches',
        muscle: 'Core',
        sets: s3(20, 16, 16),
        restTimerSeconds: 30,
      },
      {
        id: '3',
        exerciseId: 'heel-taps',
        exerciseName: 'Heel Taps',
        muscle: 'Core',
        sets: s3(20, 16, 16),
        restTimerSeconds: 30,
      },
      {
        id: '4',
        exerciseId: 'toe-crunch',
        exerciseName: 'Toe Crunches',
        muscle: 'Core',
        sets: s3(15, 12, 12),
        restTimerSeconds: 30,
      },
      {
        id: '5',
        exerciseId: 'alternating-toe-taps',
        exerciseName: 'Alternating Toe Taps',
        muscle: 'Core',
        sets: s3(20, 16, 16),
        restTimerSeconds: 30,
      },
      {
        id: '6',
        exerciseId: 'plank',
        exerciseName: 'Plank',
        muscle: 'Core',
        sets: s3(45, 45, 45),
        restTimerSeconds: 30,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'preset-core-8',
    name: 'Endurance',
    description: 'Core endurance workout with plank variations',
    tagIds: ['core'],
    tagColor: colors.workout.core,
    estimatedDuration: 40,
    difficulty: 'Advanced',
    equipment: 'No Equipment',
    category: 'core',
    localImage: CATEGORY_IMAGES.core,
    exercises: [
      {
        id: '1',
        exerciseId: 'plank',
        exerciseName: 'Plank',
        muscle: 'Core',
        sets: s3(60, 60, 45),
        restTimerSeconds: 30,
      },
      {
        id: '2',
        exerciseId: 'plank-twists',
        exerciseName: 'Plank Twists',
        muscle: 'Core',
        sets: s3(16, 14, 14),
        restTimerSeconds: 30,
      },
      {
        id: '3',
        exerciseId: 'side-plank',
        exerciseName: 'Side Plank',
        muscle: 'Core',
        sets: s3(30, 30, 30),
        restTimerSeconds: 30,
      },
      {
        id: '4',
        exerciseId: 'side-plank-dips',
        exerciseName: 'Side Plank Dips',
        muscle: 'Core',
        sets: s3(12, 10, 10),
        restTimerSeconds: 30,
      },
      {
        id: '5',
        exerciseId: 'mountain-climber',
        exerciseName: 'Mountain Climbers',
        muscle: 'Core',
        sets: s3(30, 25, 25),
        restTimerSeconds: 30,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },

  // ===========================
  // GLUTES (9 workouts)
  // ===========================
  {
    id: 'preset-glutes-1',
    name: 'Workout 1',
    description: 'Classic glute workout with hip thrusts and split squats',
    tagIds: ['glutes', 'legs'],
    tagColor: colors.workout.legs,
    estimatedDuration: 40,
    difficulty: 'Intermediate',
    equipment: 'Gym',
    category: 'glutes',
    localImage: CATEGORY_IMAGES.glutes,
    exercises: [
      {
        id: '1',
        exerciseId: 'hip-thrust-barbell',
        exerciseName: 'Hip Thrusts',
        muscle: 'Glutes',
        sets: s3(12, 10, 10, 40, 50, 50),
        restTimerSeconds: 90,
      },
      {
        id: '2',
        exerciseId: 'bulgarian-split-squat',
        exerciseName: 'Bulgarian Split Squats',
        muscle: 'Glutes',
        sets: s3(10, 10, 8, 10, 12, 12),
        restTimerSeconds: 90,
      },
      {
        id: '3',
        exerciseId: 'barbell-rdl',
        exerciseName: 'Barbell RDL',
        muscle: 'Glutes',
        sets: s3(12, 10, 10, 30, 40, 40),
        restTimerSeconds: 90,
      },
      {
        id: '4',
        exerciseId: 'cable-kickback',
        exerciseName: 'Cable Kickbacks',
        muscle: 'Glutes',
        sets: s3(12, 12, 10, 8, 10, 10),
        restTimerSeconds: 60,
      },
      {
        id: '5',
        exerciseId: 'back-extension',
        exerciseName: 'Back Extensions',
        muscle: 'Glutes',
        sets: s3(15, 12, 12),
        restTimerSeconds: 60,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'preset-glutes-2',
    name: 'Workout 2',
    description: 'Glute focused workout with glute bridges and hip abduction',
    tagIds: ['glutes', 'legs'],
    tagColor: colors.workout.legs,
    estimatedDuration: 40,
    difficulty: 'Intermediate',
    equipment: 'Gym',
    category: 'glutes',
    localImage: CATEGORY_IMAGES.glutes,
    exercises: [
      {
        id: '1',
        exerciseId: 'hip-thrust-barbell',
        exerciseName: 'Hip Thrusts',
        muscle: 'Glutes',
        sets: s3(12, 10, 10, 40, 50, 50),
        restTimerSeconds: 90,
      },
      {
        id: '2',
        exerciseId: 'kas-glute-bridge',
        exerciseName: 'Kas Glute Bridge',
        muscle: 'Glutes',
        sets: s3(12, 10, 10, 40, 50, 50),
        restTimerSeconds: 90,
      },
      {
        id: '3',
        exerciseId: 'dumbbell-rdl',
        exerciseName: 'DB RDL',
        muscle: 'Glutes',
        sets: s3(12, 10, 10, 12, 14, 14),
        restTimerSeconds: 90,
      },
      {
        id: '4',
        exerciseId: 'goblet-squat',
        exerciseName: 'DB Goblet Squat',
        muscle: 'Glutes',
        sets: s3(12, 10, 10, 14, 16, 16),
        restTimerSeconds: 90,
      },
      {
        id: '5',
        exerciseId: 'hip-abduction-machine',
        exerciseName: 'Hip Abduction',
        muscle: 'Glutes',
        sets: s3(15, 12, 12, 30, 35, 35),
        restTimerSeconds: 60,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'preset-glutes-3',
    name: 'Workout 3',
    description: 'Machine and cable glute workout',
    tagIds: ['glutes', 'legs'],
    tagColor: colors.workout.legs,
    estimatedDuration: 40,
    difficulty: 'Intermediate',
    equipment: 'Gym',
    category: 'glutes',
    localImage: CATEGORY_IMAGES.glutes,
    exercises: [
      {
        id: '1',
        exerciseId: 'hip-thrust-machine',
        exerciseName: 'Hip Thrust Machine',
        muscle: 'Glutes',
        sets: s3(12, 10, 10, 40, 50, 50),
        restTimerSeconds: 90,
      },
      {
        id: '2',
        exerciseId: 'reverse-lunge-smith',
        exerciseName: 'Reverse Lunge (Smith Machine)',
        muscle: 'Glutes',
        sets: s3(10, 10, 8, 20, 25, 25),
        restTimerSeconds: 90,
      },
      {
        id: '3',
        exerciseId: 'good-morning',
        exerciseName: 'Good Mornings',
        muscle: 'Glutes',
        sets: s3(12, 10, 10, 20, 25, 25),
        restTimerSeconds: 90,
      },
      {
        id: '4',
        exerciseId: 'hip-abduction-machine',
        exerciseName: 'Hip Abductions',
        muscle: 'Glutes',
        sets: s3(15, 12, 12, 30, 35, 35),
        restTimerSeconds: 60,
      },
      {
        id: '5',
        exerciseId: 'cable-kickback',
        exerciseName: 'Cable Kickbacks',
        muscle: 'Glutes',
        sets: s3(12, 12, 10, 8, 10, 10),
        restTimerSeconds: 60,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'preset-glutes-4',
    name: 'Workout 4',
    description: 'Glute bridge and split squat focused workout',
    tagIds: ['glutes', 'legs'],
    tagColor: colors.workout.legs,
    estimatedDuration: 40,
    difficulty: 'Intermediate',
    equipment: 'Gym',
    category: 'glutes',
    localImage: CATEGORY_IMAGES.glutes,
    exercises: [
      {
        id: '1',
        exerciseId: 'kas-glute-bridge',
        exerciseName: 'Kas Glute Bridge',
        muscle: 'Glutes',
        sets: s3(12, 10, 10, 40, 50, 50),
        restTimerSeconds: 90,
      },
      {
        id: '2',
        exerciseId: 'bulgarian-split-squat',
        exerciseName: 'Bulgarian Split Squats',
        muscle: 'Glutes',
        sets: s3(10, 10, 8, 10, 12, 12),
        restTimerSeconds: 90,
      },
      {
        id: '3',
        exerciseId: 'cable-step-up',
        exerciseName: 'Cable Step Ups',
        muscle: 'Glutes',
        sets: s3(12, 10, 10, 10, 12, 12),
        restTimerSeconds: 60,
      },
      {
        id: '4',
        exerciseId: 'cable-kickback',
        exerciseName: 'Cable Kickbacks',
        muscle: 'Glutes',
        sets: s3(12, 12, 10, 8, 10, 10),
        restTimerSeconds: 60,
      },
      {
        id: '5',
        exerciseId: 'goblet-squat',
        exerciseName: 'Goblet Squats (DB)',
        muscle: 'Glutes',
        sets: s3(12, 10, 10, 14, 16, 16),
        restTimerSeconds: 90,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'preset-glutes-5',
    name: 'Dumbbells',
    description: 'Dumbbell-only glute workout',
    tagIds: ['glutes', 'legs'],
    tagColor: colors.workout.legs,
    estimatedDuration: 35,
    difficulty: 'Intermediate',
    equipment: 'Gym',
    category: 'glutes',
    localImage: CATEGORY_IMAGES.glutes,
    exercises: [
      {
        id: '1',
        exerciseId: 'single-leg-hip-thrust',
        exerciseName: 'Single Leg Hip Thrust',
        muscle: 'Glutes',
        sets: s3(12, 10, 10),
        restTimerSeconds: 60,
      },
      {
        id: '2',
        exerciseId: 'bulgarian-split-squat',
        exerciseName: 'Bulgarian Split Squats',
        muscle: 'Glutes',
        sets: s3(10, 10, 8, 10, 12, 12),
        restTimerSeconds: 90,
      },
      {
        id: '3',
        exerciseId: 'dumbbell-b-stance-rdl',
        exerciseName: 'DB B-Stance RDL',
        muscle: 'Glutes',
        sets: s3(12, 10, 10, 12, 14, 14),
        restTimerSeconds: 90,
      },
      {
        id: '4',
        exerciseId: 'goblet-squat',
        exerciseName: 'DB Goblet Squat',
        muscle: 'Glutes',
        sets: s3(12, 10, 10, 14, 16, 16),
        restTimerSeconds: 90,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'preset-glutes-6',
    name: 'Barbell / Smith',
    description: 'Barbell and smith machine glute workout',
    tagIds: ['glutes', 'legs'],
    tagColor: colors.workout.legs,
    estimatedDuration: 40,
    difficulty: 'Intermediate',
    equipment: 'Gym',
    category: 'glutes',
    localImage: CATEGORY_IMAGES.glutes,
    exercises: [
      {
        id: '1',
        exerciseId: 'hip-thrust-barbell',
        exerciseName: 'Hip Thrust',
        muscle: 'Glutes',
        sets: s3(12, 10, 10, 40, 50, 50),
        restTimerSeconds: 90,
      },
      {
        id: '2',
        exerciseId: 'barbell-rdl',
        exerciseName: 'RDLs',
        muscle: 'Glutes',
        sets: s3(12, 10, 10, 30, 40, 40),
        restTimerSeconds: 90,
      },
      {
        id: '3',
        exerciseId: 'good-morning',
        exerciseName: 'Good Mornings',
        muscle: 'Glutes',
        sets: s3(12, 10, 10, 20, 25, 25),
        restTimerSeconds: 90,
      },
      {
        id: '4',
        exerciseId: 'step-up',
        exerciseName: 'Step Ups',
        muscle: 'Glutes',
        sets: s3(12, 10, 10, 10, 12, 12),
        restTimerSeconds: 60,
      },
      {
        id: '5',
        exerciseId: 'barbell-squat',
        exerciseName: 'Squats',
        muscle: 'Glutes',
        sets: s3(12, 10, 8, 40, 50, 50),
        restTimerSeconds: 120,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'preset-glutes-7',
    name: 'Unilateral',
    description: 'Single-leg focused glute workout for balance and symmetry',
    tagIds: ['glutes', 'legs'],
    tagColor: colors.workout.legs,
    estimatedDuration: 40,
    difficulty: 'Advanced',
    equipment: 'Gym',
    category: 'glutes',
    localImage: CATEGORY_IMAGES.glutes,
    exercises: [
      {
        id: '1',
        exerciseId: 'dumbbell-step-up',
        exerciseName: 'DB Step Ups',
        muscle: 'Glutes',
        sets: s3(10, 10, 8, 10, 12, 12),
        restTimerSeconds: 60,
      },
      {
        id: '2',
        exerciseId: 'single-leg-rdl',
        exerciseName: 'Single Leg RDL',
        muscle: 'Glutes',
        sets: s3(10, 10, 8, 10, 12, 12),
        restTimerSeconds: 60,
      },
      {
        id: '3',
        exerciseId: 'single-leg-box-squat',
        exerciseName: 'Single Leg Box Squat',
        muscle: 'Glutes',
        sets: s3(10, 8, 8),
        restTimerSeconds: 90,
      },
      {
        id: '4',
        exerciseId: 'cable-kickback',
        exerciseName: 'Cable Kickbacks',
        muscle: 'Glutes',
        sets: s3(12, 12, 10, 8, 10, 10),
        restTimerSeconds: 60,
      },
      {
        id: '5',
        exerciseId: 'single-leg-press',
        exerciseName: 'Single Leg Press',
        muscle: 'Glutes',
        sets: s3(12, 10, 10, 40, 50, 50),
        restTimerSeconds: 90,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'preset-glutes-8',
    name: 'Bilateral',
    description: 'Two-legged glute exercises for maximum load',
    tagIds: ['glutes', 'legs'],
    tagColor: colors.workout.legs,
    estimatedDuration: 40,
    difficulty: 'Intermediate',
    equipment: 'Gym',
    category: 'glutes',
    localImage: CATEGORY_IMAGES.glutes,
    exercises: [
      {
        id: '1',
        exerciseId: 'hip-thrust-machine',
        exerciseName: 'Hip Thrust Machine',
        muscle: 'Glutes',
        sets: s3(12, 10, 10, 40, 50, 50),
        restTimerSeconds: 90,
      },
      {
        id: '2',
        exerciseId: 'barbell-rdl',
        exerciseName: 'BB RDL',
        muscle: 'Glutes',
        sets: s3(12, 10, 10, 30, 40, 40),
        restTimerSeconds: 90,
      },
      {
        id: '3',
        exerciseId: 'hip-abduction-machine',
        exerciseName: 'Hip Abduction',
        muscle: 'Glutes',
        sets: s3(15, 12, 12, 30, 35, 35),
        restTimerSeconds: 60,
      },
      {
        id: '4',
        exerciseId: 'dumbbell-squat',
        exerciseName: 'DB Squat',
        muscle: 'Glutes',
        sets: s3(12, 10, 10, 12, 14, 14),
        restTimerSeconds: 90,
      },
      {
        id: '5',
        exerciseId: 'back-extension',
        exerciseName: 'Back Extensions',
        muscle: 'Glutes',
        sets: s3(15, 12, 12),
        restTimerSeconds: 60,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'preset-glutes-9',
    name: 'Compound',
    description: 'Heavy compound movements for glute strength',
    tagIds: ['glutes', 'legs'],
    tagColor: colors.workout.legs,
    estimatedDuration: 35,
    difficulty: 'Advanced',
    equipment: 'Gym',
    category: 'glutes',
    localImage: CATEGORY_IMAGES.glutes,
    exercises: [
      {
        id: '1',
        exerciseId: 'leg-press',
        exerciseName: 'Leg Press',
        muscle: 'Glutes',
        sets: s3(12, 10, 10, 80, 100, 100),
        restTimerSeconds: 90,
      },
      {
        id: '2',
        exerciseId: 'hip-thrust-barbell',
        exerciseName: 'Hip Thrust',
        muscle: 'Glutes',
        sets: s3(12, 10, 10, 40, 50, 50),
        restTimerSeconds: 90,
      },
      {
        id: '3',
        exerciseId: 'barbell-squat',
        exerciseName: 'Squat',
        muscle: 'Glutes',
        sets: s3(10, 8, 8, 40, 50, 50),
        restTimerSeconds: 120,
      },
      {
        id: '4',
        exerciseId: 'deadlift',
        exerciseName: 'Deadlift',
        muscle: 'Glutes',
        sets: s3(10, 8, 6, 50, 60, 70),
        restTimerSeconds: 120,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },

  // ===========================
  // LOWER BODY (4 workouts)
  // ===========================
  {
    id: 'preset-lower-1',
    name: 'Workout 1',
    description: 'Complete lower body workout with squats and deadlifts',
    tagIds: ['legs'],
    tagColor: colors.workout.legs,
    estimatedDuration: 40,
    difficulty: 'Intermediate',
    equipment: 'Gym',
    category: 'lower-body',
    localImage: CATEGORY_IMAGES.lowerBody,
    exercises: [
      {
        id: '1',
        exerciseId: 'barbell-squat',
        exerciseName: 'Back Squat',
        muscle: 'Legs',
        sets: s3(12, 10, 8, 40, 50, 60),
        restTimerSeconds: 120,
      },
      {
        id: '2',
        exerciseId: 'deadlift',
        exerciseName: 'Deadlift',
        muscle: 'Legs',
        sets: s3(10, 8, 6, 50, 60, 70),
        restTimerSeconds: 120,
      },
      {
        id: '3',
        exerciseId: 'lying-hamstring-curl',
        exerciseName: 'Hammy Curl (Lying)',
        muscle: 'Legs',
        sets: s3(12, 10, 10, 20, 25, 25),
        restTimerSeconds: 60,
      },
      {
        id: '4',
        exerciseId: 'leg-extension',
        exerciseName: 'Leg Extension',
        muscle: 'Legs',
        sets: s3(12, 10, 10, 25, 30, 30),
        restTimerSeconds: 60,
      },
      {
        id: '5',
        exerciseId: 'calf-raise-smith',
        exerciseName: 'Calf Raise (Smith Machine)',
        muscle: 'Legs',
        sets: s3(15, 12, 12, 30, 40, 40),
        restTimerSeconds: 60,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'preset-lower-2',
    name: 'Workout 2',
    description: 'Lower body with lunges, step ups and RDLs',
    tagIds: ['legs'],
    tagColor: colors.workout.legs,
    estimatedDuration: 50,
    difficulty: 'Intermediate',
    equipment: 'Gym',
    category: 'lower-body',
    localImage: CATEGORY_IMAGES.lowerBody,
    exercises: [
      {
        id: '1',
        exerciseId: 'leg-press',
        exerciseName: 'Leg Press',
        muscle: 'Legs',
        sets: s3(12, 10, 10, 80, 100, 100),
        restTimerSeconds: 90,
      },
      {
        id: '2',
        exerciseId: 'walking-lunge',
        exerciseName: 'Walking Lunges',
        muscle: 'Legs',
        sets: s3(12, 10, 10, 10, 12, 12),
        restTimerSeconds: 60,
      },
      {
        id: '3',
        exerciseId: 'goblet-squat',
        exerciseName: 'Goblet Squat',
        muscle: 'Legs',
        sets: s3(12, 10, 10, 14, 16, 16),
        restTimerSeconds: 90,
      },
      {
        id: '4',
        exerciseId: 'step-up',
        exerciseName: 'Step Ups',
        muscle: 'Legs',
        sets: s3(12, 10, 10, 10, 12, 12),
        restTimerSeconds: 60,
      },
      {
        id: '5',
        exerciseId: 'calf-raise-machine',
        exerciseName: 'Calf Raise Machine',
        muscle: 'Legs',
        sets: s3(15, 12, 12, 40, 50, 50),
        restTimerSeconds: 60,
      },
      {
        id: '6',
        exerciseId: 'dumbbell-rdl',
        exerciseName: 'RDL (DB)',
        muscle: 'Legs',
        sets: s3(12, 10, 10, 12, 14, 14),
        restTimerSeconds: 90,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'preset-lower-3',
    name: 'Workout 3',
    description: 'Hack squat and single-leg focused lower body',
    tagIds: ['legs'],
    tagColor: colors.workout.legs,
    estimatedDuration: 40,
    difficulty: 'Intermediate',
    equipment: 'Gym',
    category: 'lower-body',
    localImage: CATEGORY_IMAGES.lowerBody,
    exercises: [
      {
        id: '1',
        exerciseId: 'hack-squat',
        exerciseName: 'Hack Squat',
        muscle: 'Legs',
        sets: s3(12, 10, 8, 40, 50, 60),
        restTimerSeconds: 90,
      },
      {
        id: '2',
        exerciseId: 'single-leg-press',
        exerciseName: 'Single Leg Leg Press',
        muscle: 'Legs',
        sets: s3(12, 10, 10, 40, 50, 50),
        restTimerSeconds: 90,
      },
      {
        id: '3',
        exerciseId: 'leg-extension',
        exerciseName: 'Leg Extensions',
        muscle: 'Legs',
        sets: s3(12, 10, 10, 25, 30, 30),
        restTimerSeconds: 60,
      },
      {
        id: '4',
        exerciseId: 'reverse-lunge-smith',
        exerciseName: 'Reverse Lunge (Smith Machine)',
        muscle: 'Legs',
        sets: s3(10, 10, 8, 20, 25, 25),
        restTimerSeconds: 90,
      },
      {
        id: '5',
        exerciseId: 'single-leg-calf-raise',
        exerciseName: 'Single Leg Calf Raises (DB)',
        muscle: 'Legs',
        sets: s3(15, 12, 12, 8, 10, 10),
        restTimerSeconds: 45,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'preset-lower-4',
    name: 'Quad & Calf',
    description: 'Quad and calf focused lower body workout',
    tagIds: ['legs'],
    tagColor: colors.workout.legs,
    estimatedDuration: 50,
    difficulty: 'Intermediate',
    equipment: 'Gym',
    category: 'lower-body',
    localImage: CATEGORY_IMAGES.lowerBody,
    exercises: [
      {
        id: '1',
        exerciseId: 'heel-elevated-squat',
        exerciseName: 'Heel Elevated Squat',
        muscle: 'Legs',
        sets: s3(12, 10, 10, 30, 40, 40),
        restTimerSeconds: 90,
      },
      {
        id: '2',
        exerciseId: 'leg-press',
        exerciseName: 'Leg Press',
        muscle: 'Legs',
        sets: s3(12, 10, 10, 80, 100, 100),
        restTimerSeconds: 90,
      },
      {
        id: '3',
        exerciseId: 'lunge',
        exerciseName: 'Lunge',
        muscle: 'Legs',
        sets: s3(12, 10, 10, 10, 12, 12),
        restTimerSeconds: 60,
      },
      {
        id: '4',
        exerciseId: 'knee-extension',
        exerciseName: 'Knee Extension',
        muscle: 'Legs',
        sets: s3(12, 10, 10, 25, 30, 30),
        restTimerSeconds: 60,
      },
      {
        id: '5',
        exerciseId: 'single-leg-calf-raise',
        exerciseName: 'Single Leg DB Calf Raises',
        muscle: 'Legs',
        sets: s3(15, 12, 12, 8, 10, 10),
        restTimerSeconds: 45,
      },
      {
        id: '6',
        exerciseId: 'calf-raise-machine',
        exerciseName: 'Calf Raise Machine',
        muscle: 'Legs',
        sets: s3(15, 12, 12, 40, 50, 50),
        restTimerSeconds: 60,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },

  // ===========================
  // PULL (6 workouts)
  // ===========================
  {
    id: 'preset-pull-1',
    name: 'Workout 1',
    description: 'Pull day with lat pulldown, rows and curls',
    tagIds: ['back', 'arms'],
    tagColor: colors.workout.back,
    estimatedDuration: 40,
    difficulty: 'Intermediate',
    equipment: 'Gym',
    category: 'pull',
    localImage: CATEGORY_IMAGES.pull,
    exercises: [
      {
        id: '1',
        exerciseId: 'wide-grip-lat-pulldown',
        exerciseName: 'Wide Grip Lat Pull Down',
        muscle: 'Back',
        sets: s3(12, 10, 8, 30, 35, 40),
        restTimerSeconds: 90,
      },
      {
        id: '2',
        exerciseId: 'bent-over-dumbbell-row',
        exerciseName: 'Bent Over DB Row',
        muscle: 'Back',
        sets: s3(12, 10, 10, 12, 14, 14),
        restTimerSeconds: 90,
      },
      {
        id: '3',
        exerciseId: 'face-pull',
        exerciseName: 'Face Pull',
        muscle: 'Back',
        sets: s3(15, 12, 12, 15, 18, 18),
        restTimerSeconds: 60,
      },
      {
        id: '4',
        exerciseId: 'barbell-bicep-curl',
        exerciseName: 'BB Bicep Curl',
        muscle: 'Arms',
        sets: s3(12, 10, 10, 15, 20, 20),
        restTimerSeconds: 60,
      },
      {
        id: '5',
        exerciseId: 'hammer-curl',
        exerciseName: 'Hammer Curl',
        muscle: 'Arms',
        sets: s3(12, 10, 10, 8, 10, 10),
        restTimerSeconds: 60,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'preset-pull-2',
    name: 'Workout 2',
    description: 'Pull workout with assisted pull ups and cable work',
    tagIds: ['back', 'arms'],
    tagColor: colors.workout.back,
    estimatedDuration: 40,
    difficulty: 'Intermediate',
    equipment: 'Gym',
    category: 'pull',
    localImage: CATEGORY_IMAGES.pull,
    exercises: [
      {
        id: '1',
        exerciseId: 'assisted-pull-up',
        exerciseName: 'Assisted Pull Ups',
        muscle: 'Back',
        sets: s3(10, 8, 8),
        restTimerSeconds: 90,
      },
      {
        id: '2',
        exerciseId: 'seated-cable-row',
        exerciseName: 'Seated Cable Row',
        muscle: 'Back',
        sets: s3(12, 10, 10, 25, 30, 30),
        restTimerSeconds: 90,
      },
      {
        id: '3',
        exerciseId: 'straight-arm-pulldown',
        exerciseName: 'Straight Arm Pull Down',
        muscle: 'Back',
        sets: s3(12, 10, 10, 15, 20, 20),
        restTimerSeconds: 60,
      },
      {
        id: '4',
        exerciseId: 'dumbbell-bicep-curl',
        exerciseName: 'Bicep Curl (DB)',
        muscle: 'Arms',
        sets: s3(12, 10, 10, 8, 10, 10),
        restTimerSeconds: 60,
      },
      {
        id: '5',
        exerciseId: 'cable-curl',
        exerciseName: 'Cable Curls',
        muscle: 'Arms',
        sets: s3(12, 10, 10, 10, 12, 12),
        restTimerSeconds: 60,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'preset-pull-3',
    name: 'Workout 3',
    description: 'Close grip focused pull workout',
    tagIds: ['back', 'arms'],
    tagColor: colors.workout.back,
    estimatedDuration: 40,
    difficulty: 'Intermediate',
    equipment: 'Gym',
    category: 'pull',
    localImage: CATEGORY_IMAGES.pull,
    exercises: [
      {
        id: '1',
        exerciseId: 'close-grip-lat-pulldown',
        exerciseName: 'Close Grip Lat Pull Down',
        muscle: 'Back',
        sets: s3(12, 10, 8, 30, 35, 40),
        restTimerSeconds: 90,
      },
      {
        id: '2',
        exerciseId: 'single-arm-machine-row',
        exerciseName: 'Single Arm Machine Row',
        muscle: 'Back',
        sets: s3(12, 10, 10, 20, 25, 25),
        restTimerSeconds: 90,
      },
      {
        id: '3',
        exerciseId: 'bent-over-barbell-row',
        exerciseName: 'Bent Over BB Row',
        muscle: 'Back',
        sets: s3(12, 10, 8, 25, 30, 35),
        restTimerSeconds: 90,
      },
      {
        id: '4',
        exerciseId: 'ez-bar-bicep-curl',
        exerciseName: 'EZ Bar Bicep Curl',
        muscle: 'Arms',
        sets: s3(12, 10, 10, 12, 15, 15),
        restTimerSeconds: 60,
      },
      {
        id: '5',
        exerciseId: 'cable-curl',
        exerciseName: 'Cable Curls',
        muscle: 'Arms',
        sets: s3(12, 10, 10, 10, 12, 12),
        restTimerSeconds: 60,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'preset-pull-4',
    name: 'Workout 4',
    description: 'Pull ups, rows and rear delts',
    tagIds: ['back', 'arms'],
    tagColor: colors.workout.back,
    estimatedDuration: 40,
    difficulty: 'Intermediate',
    equipment: 'Gym',
    category: 'pull',
    localImage: CATEGORY_IMAGES.pull,
    exercises: [
      {
        id: '1',
        exerciseId: 'band-assisted-pull-up',
        exerciseName: 'Band Assisted Pull Ups',
        muscle: 'Back',
        sets: s3(8, 8, 6),
        restTimerSeconds: 90,
      },
      {
        id: '2',
        exerciseId: 'close-grip-lat-pulldown',
        exerciseName: 'Close Grip Pull Down',
        muscle: 'Back',
        sets: s3(12, 10, 8, 30, 35, 40),
        restTimerSeconds: 90,
      },
      {
        id: '3',
        exerciseId: 'bent-over-dumbbell-row',
        exerciseName: 'Bent Over DB Row',
        muscle: 'Back',
        sets: s3(12, 10, 10, 12, 14, 14),
        restTimerSeconds: 90,
      },
      {
        id: '4',
        exerciseId: 'rear-delt-fly',
        exerciseName: 'Rear Delt Fly',
        muscle: 'Shoulders',
        sets: s3(15, 12, 12, 6, 8, 8),
        restTimerSeconds: 60,
      },
      {
        id: '5',
        exerciseId: 'bicep-curl-cable-superset',
        exerciseName: 'Bicep Curls + Cable Curls (Superset)',
        muscle: 'Arms',
        sets: s3(12, 10, 10, 8, 10, 10),
        restTimerSeconds: 60,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'preset-pull-5',
    name: 'Workout 5',
    description: 'Rows, flies and curls pull workout',
    tagIds: ['back', 'arms'],
    tagColor: colors.workout.back,
    estimatedDuration: 40,
    difficulty: 'Intermediate',
    equipment: 'Gym',
    category: 'pull',
    localImage: CATEGORY_IMAGES.pull,
    exercises: [
      {
        id: '1',
        exerciseId: 'bent-over-barbell-row',
        exerciseName: 'Bent Over Rows',
        muscle: 'Back',
        sets: s3(12, 10, 8, 25, 30, 35),
        restTimerSeconds: 90,
      },
      {
        id: '2',
        exerciseId: 'single-arm-cable-row',
        exerciseName: 'Single Arm Cable Row',
        muscle: 'Back',
        sets: s3(12, 10, 10, 15, 18, 18),
        restTimerSeconds: 60,
      },
      {
        id: '3',
        exerciseId: 'reverse-fly',
        exerciseName: 'Reverse Flies',
        muscle: 'Shoulders',
        sets: s3(15, 12, 12, 6, 8, 8),
        restTimerSeconds: 60,
      },
      {
        id: '4',
        exerciseId: 'barbell-bicep-curl',
        exerciseName: 'Bicep Curl (BB)',
        muscle: 'Arms',
        sets: s3(12, 10, 10, 15, 20, 20),
        restTimerSeconds: 60,
      },
      {
        id: '5',
        exerciseId: 'preacher-curl',
        exerciseName: 'Preacher Curl',
        muscle: 'Arms',
        sets: s3(12, 10, 10, 8, 10, 10),
        restTimerSeconds: 60,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'preset-pull-6',
    name: 'Workout 6',
    description: 'Machine and cable pull workout',
    tagIds: ['back', 'arms'],
    tagColor: colors.workout.back,
    estimatedDuration: 50,
    difficulty: 'Intermediate',
    equipment: 'Gym',
    category: 'pull',
    localImage: CATEGORY_IMAGES.pull,
    exercises: [
      {
        id: '1',
        exerciseId: 'machine-row',
        exerciseName: 'Machine Row',
        muscle: 'Back',
        sets: s3(12, 10, 10, 30, 35, 35),
        restTimerSeconds: 90,
      },
      {
        id: '2',
        exerciseId: 'lat-pulldown',
        exerciseName: 'Lat Pull Down',
        muscle: 'Back',
        sets: s3(12, 10, 8, 30, 35, 40),
        restTimerSeconds: 90,
      },
      {
        id: '3',
        exerciseId: 'face-pull',
        exerciseName: 'Face Pull',
        muscle: 'Back',
        sets: s3(15, 12, 12, 15, 18, 18),
        restTimerSeconds: 60,
      },
      {
        id: '4',
        exerciseId: 'preacher-curl',
        exerciseName: 'Preacher Curl',
        muscle: 'Arms',
        sets: s3(12, 10, 10, 8, 10, 10),
        restTimerSeconds: 60,
      },
      {
        id: '5',
        exerciseId: 'cable-bicep-curl',
        exerciseName: 'Cable Bicep Curl',
        muscle: 'Arms',
        sets: s3(12, 10, 10, 10, 12, 12),
        restTimerSeconds: 60,
      },
      {
        id: '6',
        exerciseId: 'reverse-fly-dumbbell',
        exerciseName: 'Reverse Fly (Dumbbells)',
        muscle: 'Shoulders',
        sets: s3(15, 12, 12, 6, 8, 8),
        restTimerSeconds: 60,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },

  // ===========================
  // PUSH (4 workouts)
  // ===========================
  {
    id: 'preset-push-1',
    name: 'Workout 1',
    description: 'Shoulder press, chest flies and tricep work',
    tagIds: ['chest', 'shoulders', 'arms'],
    tagColor: colors.workout.chest,
    estimatedDuration: 40,
    difficulty: 'Intermediate',
    equipment: 'Gym',
    category: 'push',
    localImage: CATEGORY_IMAGES.push,
    exercises: [
      {
        id: '1',
        exerciseId: 'dumbbell-shoulder-press',
        exerciseName: 'Shoulder Press',
        muscle: 'Shoulders',
        sets: s3(12, 10, 10, 8, 10, 10),
        restTimerSeconds: 90,
      },
      {
        id: '2',
        exerciseId: 'lateral-front-raise-superset',
        exerciseName: 'Lat & Front Raise (Superset)',
        muscle: 'Shoulders',
        sets: s3(12, 10, 10, 5, 6, 6),
        restTimerSeconds: 60,
      },
      {
        id: '3',
        exerciseId: 'chest-fly',
        exerciseName: 'Chest Flies',
        muscle: 'Chest',
        sets: s3(12, 10, 10, 8, 10, 10),
        restTimerSeconds: 60,
      },
      {
        id: '4',
        exerciseId: 'tricep-cable-pushdown',
        exerciseName: 'Tricep Cable Push Down',
        muscle: 'Arms',
        sets: s3(12, 10, 10, 15, 20, 20),
        restTimerSeconds: 60,
      },
      {
        id: '5',
        exerciseId: 'standing-tricep-kickback',
        exerciseName: 'Standing Tricep Kickbacks',
        muscle: 'Arms',
        sets: s3(12, 10, 10, 5, 6, 6),
        restTimerSeconds: 60,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'preset-push-2',
    name: 'Workout 2',
    description: 'Machine-based push workout',
    tagIds: ['chest', 'shoulders', 'arms'],
    tagColor: colors.workout.chest,
    estimatedDuration: 40,
    difficulty: 'Intermediate',
    equipment: 'Gym',
    category: 'push',
    localImage: CATEGORY_IMAGES.push,
    exercises: [
      {
        id: '1',
        exerciseId: 'shoulder-press-machine',
        exerciseName: 'Shoulder Press Machine',
        muscle: 'Shoulders',
        sets: s3(12, 10, 10, 15, 20, 20),
        restTimerSeconds: 90,
      },
      {
        id: '2',
        exerciseId: 'lateral-raise-machine',
        exerciseName: 'Lateral Raise Machine',
        muscle: 'Shoulders',
        sets: s3(12, 10, 10, 15, 18, 18),
        restTimerSeconds: 60,
      },
      {
        id: '3',
        exerciseId: 'seated-incline-front-raise',
        exerciseName: 'Seated Incline Front Raises',
        muscle: 'Shoulders',
        sets: s3(12, 10, 10, 5, 6, 6),
        restTimerSeconds: 60,
      },
      {
        id: '4',
        exerciseId: 'tricep-cable-overhead',
        exerciseName: 'Tricep Cable Overhead',
        muscle: 'Arms',
        sets: s3(12, 10, 10, 12, 15, 15),
        restTimerSeconds: 60,
      },
      {
        id: '5',
        exerciseId: 'tricep-pushdown',
        exerciseName: 'Tricep Push Down (Cable)',
        muscle: 'Arms',
        sets: s3(12, 10, 10, 15, 20, 20),
        restTimerSeconds: 60,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'preset-push-3',
    name: 'Workout 3',
    description: 'Cable lateral raises, overhead press and dips',
    tagIds: ['chest', 'shoulders', 'arms'],
    tagColor: colors.workout.chest,
    estimatedDuration: 40,
    difficulty: 'Intermediate',
    equipment: 'Gym',
    category: 'push',
    localImage: CATEGORY_IMAGES.push,
    exercises: [
      {
        id: '1',
        exerciseId: 'cable-lateral-raise',
        exerciseName: 'Cable Lateral Raise',
        muscle: 'Shoulders',
        sets: s3(12, 10, 10, 5, 6, 6),
        restTimerSeconds: 60,
      },
      {
        id: '2',
        exerciseId: 'barbell-overhead-press',
        exerciseName: 'BB Overhead Press',
        muscle: 'Shoulders',
        sets: s3(10, 8, 8, 20, 25, 25),
        restTimerSeconds: 90,
      },
      {
        id: '3',
        exerciseId: 'seated-incline-lateral-raise',
        exerciseName: 'Seated Incline Lateral Raise',
        muscle: 'Shoulders',
        sets: s3(12, 10, 10, 4, 5, 5),
        restTimerSeconds: 60,
      },
      {
        id: '4',
        exerciseId: 'chest-fly',
        exerciseName: 'Chest Flies',
        muscle: 'Chest',
        sets: s3(12, 10, 10, 8, 10, 10),
        restTimerSeconds: 60,
      },
      {
        id: '5',
        exerciseId: 'tricep-dip',
        exerciseName: 'Tricep Dips',
        muscle: 'Arms',
        sets: s3(12, 10, 10),
        restTimerSeconds: 60,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'preset-push-4',
    name: 'Workout 4',
    description: 'Dumbbell focused push workout',
    tagIds: ['chest', 'shoulders', 'arms'],
    tagColor: colors.workout.chest,
    estimatedDuration: 40,
    difficulty: 'Intermediate',
    equipment: 'Gym',
    category: 'push',
    localImage: CATEGORY_IMAGES.push,
    exercises: [
      {
        id: '1',
        exerciseId: 'dumbbell-chest-press',
        exerciseName: 'DB Chest Press',
        muscle: 'Chest',
        sets: s3(12, 10, 10, 10, 12, 12),
        restTimerSeconds: 90,
      },
      {
        id: '2',
        exerciseId: 'dumbbell-shoulder-press',
        exerciseName: 'DB Shoulder Press',
        muscle: 'Shoulders',
        sets: s3(12, 10, 10, 8, 10, 10),
        restTimerSeconds: 90,
      },
      {
        id: '3',
        exerciseId: 'front-lateral-raise-superset',
        exerciseName: 'Front Raise / Lat Raise DB (Superset)',
        muscle: 'Shoulders',
        sets: s3(12, 10, 10, 5, 6, 6),
        restTimerSeconds: 60,
      },
      {
        id: '4',
        exerciseId: 'tricep-overhead-dumbbell',
        exerciseName: 'Tricep Overhead (DB)',
        muscle: 'Arms',
        sets: s3(12, 10, 10, 8, 10, 10),
        restTimerSeconds: 60,
      },
      {
        id: '5',
        exerciseId: 'single-arm-tricep-pushdown',
        exerciseName: 'Tricep Single Arm Push Down',
        muscle: 'Arms',
        sets: s3(12, 10, 10, 8, 10, 10),
        restTimerSeconds: 60,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },

  // ===========================
  // UPPER BODY (4 workouts)
  // ===========================
  {
    id: 'preset-upper-1',
    name: 'Workout 1',
    description: 'Balanced upper body with pull and push movements',
    tagIds: ['chest', 'back', 'shoulders', 'arms'],
    tagColor: colors.workout.fullBody,
    estimatedDuration: 50,
    difficulty: 'Intermediate',
    equipment: 'Gym',
    category: 'upper-body',
    localImage: CATEGORY_IMAGES.upperBody,
    exercises: [
      {
        id: '1',
        exerciseId: 'lat-pulldown',
        exerciseName: 'Lat Pull Down',
        muscle: 'Back',
        sets: s3(12, 10, 8, 30, 35, 40),
        restTimerSeconds: 90,
      },
      {
        id: '2',
        exerciseId: 'dumbbell-shoulder-press',
        exerciseName: 'Shoulder Press',
        muscle: 'Shoulders',
        sets: s3(12, 10, 10, 8, 10, 10),
        restTimerSeconds: 90,
      },
      {
        id: '3',
        exerciseId: 'cable-lateral-raise',
        exerciseName: 'Lat Raise (Cable)',
        muscle: 'Shoulders',
        sets: s3(12, 10, 10, 5, 6, 6),
        restTimerSeconds: 60,
      },
      {
        id: '4',
        exerciseId: 'cable-row',
        exerciseName: 'Cable Rows',
        muscle: 'Back',
        sets: s3(12, 10, 10, 25, 30, 30),
        restTimerSeconds: 90,
      },
      {
        id: '5',
        exerciseId: 'bicep-curl',
        exerciseName: 'Bicep Curl',
        muscle: 'Arms',
        sets: s3(12, 10, 10, 8, 10, 10),
        restTimerSeconds: 60,
      },
      {
        id: '6',
        exerciseId: 'tricep-pushdown',
        exerciseName: 'Tricep Pushdown',
        muscle: 'Arms',
        sets: s3(12, 10, 10, 15, 20, 20),
        restTimerSeconds: 60,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'preset-upper-2',
    name: 'Workout 2',
    description: 'Pull up and row focused upper body',
    tagIds: ['chest', 'back', 'shoulders', 'arms'],
    tagColor: colors.workout.fullBody,
    estimatedDuration: 50,
    difficulty: 'Intermediate',
    equipment: 'Gym',
    category: 'upper-body',
    localImage: CATEGORY_IMAGES.upperBody,
    exercises: [
      {
        id: '1',
        exerciseId: 'band-assisted-pull-up',
        exerciseName: 'Pull Ups (Band Assisted)',
        muscle: 'Back',
        sets: s3(8, 8, 6),
        restTimerSeconds: 90,
      },
      {
        id: '2',
        exerciseId: 'bent-over-barbell-row',
        exerciseName: 'Bent Over Row (BB)',
        muscle: 'Back',
        sets: s3(12, 10, 8, 25, 30, 35),
        restTimerSeconds: 90,
      },
      {
        id: '3',
        exerciseId: 'rear-delt-fly',
        exerciseName: 'Rear Delt Flies',
        muscle: 'Shoulders',
        sets: s3(15, 12, 12, 6, 8, 8),
        restTimerSeconds: 60,
      },
      {
        id: '4',
        exerciseId: 'shoulder-press-machine',
        exerciseName: 'Shoulder Press Machine',
        muscle: 'Shoulders',
        sets: s3(12, 10, 10, 15, 20, 20),
        restTimerSeconds: 90,
      },
      {
        id: '5',
        exerciseId: 'bicep-curl-cable-db-superset',
        exerciseName: 'Bicep Curl Cable & DB (Superset)',
        muscle: 'Arms',
        sets: s3(12, 10, 10, 8, 10, 10),
        restTimerSeconds: 60,
      },
      {
        id: '6',
        exerciseId: 'tricep-cable-overhead',
        exerciseName: 'Tricep Overhead (Cable)',
        muscle: 'Arms',
        sets: s3(12, 10, 10, 12, 15, 15),
        restTimerSeconds: 60,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'preset-upper-3',
    name: 'Machines',
    description: 'Machine-only upper body workout',
    tagIds: ['chest', 'back', 'shoulders', 'arms'],
    tagColor: colors.workout.fullBody,
    estimatedDuration: 40,
    difficulty: 'Beginner',
    equipment: 'Gym',
    category: 'upper-body',
    localImage: CATEGORY_IMAGES.upperBody,
    exercises: [
      {
        id: '1',
        exerciseId: 'shoulder-press-machine',
        exerciseName: 'Shoulder Press Machine',
        muscle: 'Shoulders',
        sets: s3(12, 10, 10, 15, 20, 20),
        restTimerSeconds: 90,
      },
      {
        id: '2',
        exerciseId: 'chest-press-machine',
        exerciseName: 'Chest Press Machine',
        muscle: 'Chest',
        sets: s3(12, 10, 10, 20, 25, 25),
        restTimerSeconds: 90,
      },
      {
        id: '3',
        exerciseId: 'machine-row',
        exerciseName: 'Machine Row',
        muscle: 'Back',
        sets: s3(12, 10, 10, 30, 35, 35),
        restTimerSeconds: 90,
      },
      {
        id: '4',
        exerciseId: 'machine-lateral-raise',
        exerciseName: 'Machine Lat Raise',
        muscle: 'Shoulders',
        sets: s3(12, 10, 10, 15, 18, 18),
        restTimerSeconds: 60,
      },
      {
        id: '5',
        exerciseId: 'machine-preacher-curl',
        exerciseName: 'Machine Preacher Curl',
        muscle: 'Arms',
        sets: s3(12, 10, 10, 10, 12, 12),
        restTimerSeconds: 60,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'preset-upper-4',
    name: 'Workout 4',
    description: 'Barbell and dumbbell upper body workout',
    tagIds: ['chest', 'back', 'shoulders', 'arms'],
    tagColor: colors.workout.fullBody,
    estimatedDuration: 50,
    difficulty: 'Intermediate',
    equipment: 'Gym',
    category: 'upper-body',
    localImage: CATEGORY_IMAGES.upperBody,
    exercises: [
      {
        id: '1',
        exerciseId: 'barbell-shoulder-press',
        exerciseName: 'Barbell Shoulder Press',
        muscle: 'Shoulders',
        sets: s3(10, 8, 8, 20, 25, 25),
        restTimerSeconds: 90,
      },
      {
        id: '2',
        exerciseId: 'close-grip-lat-pulldown',
        exerciseName: 'Close Grip Lat Pull Down',
        muscle: 'Back',
        sets: s3(12, 10, 8, 30, 35, 40),
        restTimerSeconds: 90,
      },
      {
        id: '3',
        exerciseId: 'dumbbell-bench-press',
        exerciseName: 'DB Bench Press',
        muscle: 'Chest',
        sets: s3(12, 10, 10, 12, 14, 14),
        restTimerSeconds: 90,
      },
      {
        id: '4',
        exerciseId: 'lat-front-raise-superset',
        exerciseName: 'Lat Raise & Front Raise (Superset)',
        muscle: 'Shoulders',
        sets: s3(12, 10, 10, 5, 6, 6),
        restTimerSeconds: 60,
      },
      {
        id: '5',
        exerciseId: 'hammer-curl',
        exerciseName: 'Hammer Curls',
        muscle: 'Arms',
        sets: s3(12, 10, 10, 8, 10, 10),
        restTimerSeconds: 60,
      },
      {
        id: '6',
        exerciseId: 'skull-crusher',
        exerciseName: 'Skull Crushers',
        muscle: 'Arms',
        sets: s3(12, 10, 10, 8, 10, 10),
        restTimerSeconds: 60,
      },
    ],
    isPreset: true,
    createdAt: new Date().toISOString(),
  },
];
